name: ðŸš€ Deploy master on push with FTP

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      # - name: Install composer dependencies
      #   run: composer install

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b7_34048879
          # ftp password
          password: ${{ secrets.ftp_password }}
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /soft-installer.22web.org/htdocs/
          #
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt
